---
language: node_js
sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

jobs:
  fail_fast: true
  include:
    - stage: "Tests"
      node_js: stable
      before_install:
        - npm config set spin false
        - npm install -g yarn
        - npm install -g codecov
        - npm install -g greenkeeper-lockfile@1
        - npm install -g @commitlint/travis-cli
        - yarn --version
      install:
        - if [[ $TRAVIS_BRANCH =~ greenkeeper || $TRAVIS_PULL_REQUEST_BRANCH =~ greenkeeper ]]; then yarn; else yarn --frozen-lockfile; fi
      before_script:
        - greenkeeper-lockfile-update
      script:
        - commitlint-travis
        - yarn lint:js
        - yarn test
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - codecov --file=coverage/lcov.info

    - stage: "Regression Tests"
      node_js: "lts/carbon"
    - node_js: "lts/dubnium"

    - stage: "Release"
      node_js: stable
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - yarn remove husky
        script:
          - npx semantic-release

before_install:
  - npm install -g yarn
  - yarn --version

script:
  - yarn test

stages:
  - "Tests"
  - "Regression Tests"
  - name: "Release"
    if: branch = master

